name: OBS Service Trigger
run-name: ${{ github.actor }} is triggering a service run on OBS
on: [push]
jobs:
  trigger_service:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          OBS_SERVICE_TOKEN: ${{ secrets.OBS_SERVICE_TOKEN }}
        run: |
          curl -H "Authorization: Token $OBS_SERVICE_TOKEN" -X POST https://api.opensuse.org/trigger/runservice
